// <auto-generated />
using EldredBrown.ProFootball.Net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EldredBrown.ProFootball.Net.Data.Migrations
{
    [DbContext(typeof(ProFootballDbContext))]
    partial class ProFootballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Association", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstSeasonId")
                        .HasColumnType("int")
                        .HasColumnName("first_season_id");

                    b.Property<int?>("LastSeasonId")
                        .HasColumnType("int")
                        .HasColumnName("last_season_id");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("long_name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("short_name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FirstSeasonId" }, "IX_FK_Association_Season_FirstSeasonId");

                    b.HasIndex(new[] { "LastSeasonId" }, "IX_FK_Association_Season_LastSeasonId");

                    b.HasIndex(new[] { "LongName" }, "UQ_Association_LongName")
                        .IsUnique();

                    b.HasIndex(new[] { "ShortName" }, "UQ_Association_ShortName")
                        .IsUnique();

                    b.ToTable("Association", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("guest_name");

                    b.Property<int>("GuestScore")
                        .HasColumnType("int")
                        .HasColumnName("guest_score");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("host_name");

                    b.Property<int>("HostScore")
                        .HasColumnType("int")
                        .HasColumnName("host_score");

                    b.Property<bool>("IsPlayoff")
                        .HasColumnType("bit")
                        .HasColumnName("is_playoff");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("notes");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<int>("Week")
                        .HasColumnType("int")
                        .HasColumnName("week");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SeasonId" }, "IX_FK_Game_Season_SeasonId");

                    b.HasIndex(new[] { "SeasonId", "Week", "GuestName", "HostName" }, "UQ_Game_Season_Week_Teams")
                        .IsUnique();

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.LeagueSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AveragePoints")
                        .HasColumnType("decimal(18, 16)")
                        .HasColumnName("average_points");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int")
                        .HasColumnName("league_id");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int")
                        .HasColumnName("total_games");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "LeagueId" }, "IX_FK_LeagueSeason_League_LeagueId");

                    b.HasIndex(new[] { "SeasonId" }, "IX_FK_LeagueSeason_Season_SeasonId");

                    b.HasIndex(new[] { "LeagueId", "SeasonId" }, "UQ_LeagueSeason_LeagueId_SeasonId")
                        .IsUnique();

                    b.ToTable("LeagueSeason", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.LeagueSeasonTotals", b =>
                {
                    b.Property<decimal?>("AveragePoints")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("average_points");

                    b.Property<int?>("TotalGames")
                        .HasColumnType("int")
                        .HasColumnName("total_games");

                    b.Property<int?>("TotalPoints")
                        .HasColumnType("int")
                        .HasColumnName("total_points");

                    b.Property<int?>("WeekCount")
                        .HasColumnType("int")
                        .HasColumnName("week_count");

                    b.ToTable("LeagueSeasonTotals", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.RankingsDefensiveTeamSeason", b =>
                {
                    b.Property<decimal?>("DefensiveAverage")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("defensive_average");

                    b.Property<decimal?>("DefensiveFactor")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("defensive_factor");

                    b.Property<decimal?>("DefensiveIndex")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("defensive_index");

                    b.Property<decimal?>("FinalExpectedWinningPercentage")
                        .HasColumnType("decimal(18,17)")
                        .HasColumnName("final_expected_winning_percentage");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<decimal?>("OffensiveAverage")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("offensive_average");

                    b.Property<decimal?>("OffensiveFactor")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("offensive_factor");

                    b.Property<decimal?>("OffensiveIndex")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("offensive_index");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("string")
                        .HasColumnName("team_name");

                    b.Property<int>("Ties")
                        .HasColumnType("int")
                        .HasColumnName("ties");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.ToTable("DefensiveRankings", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.RankingsOffensiveTeamSeason", b =>
                {
                    b.Property<decimal?>("DefensiveAverage")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("defensive_average");

                    b.Property<decimal?>("DefensiveFactor")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("defensive_factor");

                    b.Property<decimal?>("DefensiveIndex")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("defensive_index");

                    b.Property<decimal?>("FinalExpectedWinningPercentage")
                        .HasColumnType("decimal(18,17)")
                        .HasColumnName("final_expected_winning_percentage");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<decimal?>("OffensiveAverage")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("offensive_average");

                    b.Property<decimal?>("OffensiveFactor")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("offensive_factor");

                    b.Property<decimal?>("OffensiveIndex")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("offensive_index");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("string")
                        .HasColumnName("team_name");

                    b.Property<int>("Ties")
                        .HasColumnType("int")
                        .HasColumnName("ties");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.ToTable("OffensiveRankings", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.RankingsTotalTeamSeason", b =>
                {
                    b.Property<decimal?>("DefensiveAverage")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("defensive_average");

                    b.Property<decimal?>("DefensiveFactor")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("defensive_factor");

                    b.Property<decimal?>("DefensiveIndex")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("defensive_index");

                    b.Property<decimal?>("FinalExpectedWinningPercentage")
                        .HasColumnType("decimal(18,17)")
                        .HasColumnName("final_expected_winning_percentage");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<decimal?>("OffensiveAverage")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("offensive_average");

                    b.Property<decimal?>("OffensiveFactor")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("offensive_factor");

                    b.Property<decimal?>("OffensiveIndex")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("offensive_index");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("string")
                        .HasColumnName("team_name");

                    b.Property<int>("Ties")
                        .HasColumnType("int")
                        .HasColumnName("ties");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.ToTable("TotalRankings", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumOfWeeksCompleted")
                        .HasColumnType("int")
                        .HasColumnName("num_of_weeks_completed");

                    b.Property<int>("NumOfWeeksScheduled")
                        .HasColumnType("int")
                        .HasColumnName("num_of_weeks_scheduled");

                    b.HasKey("Id");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.StandingsTeamSeason", b =>
                {
                    b.Property<decimal?>("AvgPointsAgainst")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("avg_points_against");

                    b.Property<decimal?>("AvgPointsFor")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("avg_points_for");

                    b.Property<decimal?>("ExpectedLosses")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("expected_losses");

                    b.Property<decimal?>("ExpectedWins")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("expected_wins");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("points_against");

                    b.Property<int>("PointsFor")
                        .HasColumnType("int")
                        .HasColumnName("points_for");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("string")
                        .HasColumnName("team");

                    b.Property<int>("Ties")
                        .HasColumnType("int")
                        .HasColumnName("ties");

                    b.Property<decimal?>("WinningPercentage")
                        .HasColumnType("decimal(18,17)")
                        .HasColumnName("winning_percentage");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.ToTable("SeasonStandings", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_Team_Name")
                        .IsUnique();

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociationId")
                        .HasColumnType("int")
                        .HasColumnName("association_id");

                    b.Property<int?>("ConferenceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DefensiveAverage")
                        .HasColumnType("decimal(18, 15)")
                        .HasColumnName("defensive_average");

                    b.Property<decimal?>("DefensiveFactor")
                        .HasColumnType("decimal(18, 14)")
                        .HasColumnName("defensive_factor");

                    b.Property<decimal?>("DefensiveIndex")
                        .HasColumnType("decimal(18, 15)")
                        .HasColumnName("defensive_index");

                    b.Property<int?>("DivisionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedLosses")
                        .HasColumnType("decimal(18, 16)")
                        .HasColumnName("expected_losses");

                    b.Property<decimal>("ExpectedWins")
                        .HasColumnType("decimal(18, 16)")
                        .HasColumnName("expected_wins");

                    b.Property<decimal?>("FinalExpectedWinningPercentage")
                        .HasColumnType("decimal(18, 17)")
                        .HasColumnName("final_expected_winning_percentage");

                    b.Property<int>("Games")
                        .HasColumnType("int")
                        .HasColumnName("games");

                    b.Property<int>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<decimal?>("OffensiveAverage")
                        .HasColumnType("decimal(18, 15)")
                        .HasColumnName("offensive_average");

                    b.Property<decimal?>("OffensiveFactor")
                        .HasColumnType("decimal(18, 14)")
                        .HasColumnName("offensive_factor");

                    b.Property<decimal?>("OffensiveIndex")
                        .HasColumnType("decimal(18, 15)")
                        .HasColumnName("offensive_index");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("points_against");

                    b.Property<int>("PointsFor")
                        .HasColumnType("int")
                        .HasColumnName("points_for");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("Ties")
                        .HasColumnType("int")
                        .HasColumnName("ties");

                    b.Property<int>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AssociationId" }, "IX_FK_TeamSeason_Association_AssociationId");

                    b.HasIndex(new[] { "ConferenceId" }, "IX_FK_TeamSeason_Conference_ConferenceId");

                    b.HasIndex(new[] { "DivisionId" }, "IX_FK_TeamSeason_Division_DivisionId");

                    b.HasIndex(new[] { "SeasonId" }, "IX_FK_TeamSeason_Season_SeasonId");

                    b.HasIndex(new[] { "TeamId" }, "IX_FK_TeamSeason_Team_TeamId");

                    b.HasIndex(new[] { "TeamId", "SeasonId" }, "UQ_TeamSeason_AssociationId_SeasonId")
                        .IsUnique();

                    b.ToTable("TeamSeason", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeasonOpponentProfile", b =>
                {
                    b.Property<int?>("GamePointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("game_points_against");

                    b.Property<int?>("GamePointsFor")
                        .HasColumnType("int")
                        .HasColumnName("game_points_for");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("opponent");

                    b.Property<int?>("OpponentLosses")
                        .HasColumnType("int")
                        .HasColumnName("opponent_losses");

                    b.Property<int?>("OpponentTies")
                        .HasColumnType("int")
                        .HasColumnName("opponent_ties");

                    b.Property<int?>("OpponentWeightedGames")
                        .HasColumnType("int")
                        .HasColumnName("opponent_weighted_games");

                    b.Property<int?>("OpponentWeightedPointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("opponent_weighted_points_against");

                    b.Property<int?>("OpponentWeightedPointsFor")
                        .HasColumnType("int")
                        .HasColumnName("opponent_weighted_points_for");

                    b.Property<decimal?>("OpponentWinningPercentage")
                        .HasColumnType("decimal(18,17)")
                        .HasColumnName("opponent_winning_percentage");

                    b.Property<int?>("OpponentWins")
                        .HasColumnType("int")
                        .HasColumnName("opponent_wins");

                    b.ToTable("TeamSeasonScheduleProfile", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeasonScheduleAverages", b =>
                {
                    b.Property<decimal?>("PointsAgainst")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("avg_points_against");

                    b.Property<decimal?>("PointsFor")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("avg_points_for");

                    b.Property<decimal?>("SchedulePointsAgainst")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("avg_schedule_points_against");

                    b.Property<decimal?>("SchedulePointsFor")
                        .HasColumnType("decimal(18,16)")
                        .HasColumnName("avg_schedule_points_for");

                    b.ToTable("TeamSeasonScheduleAverages", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeasonScheduleTotals", b =>
                {
                    b.Property<int?>("Games")
                        .HasColumnType("int")
                        .HasColumnName("games");

                    b.Property<int?>("PointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("points_against");

                    b.Property<int?>("PointsFor")
                        .HasColumnType("int")
                        .HasColumnName("points_for");

                    b.Property<int?>("ScheduleGames")
                        .HasColumnType("int")
                        .HasColumnName("schedule_games");

                    b.Property<int?>("ScheduleLosses")
                        .HasColumnType("int")
                        .HasColumnName("schedule_losses");

                    b.Property<int?>("SchedulePointsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("schedule_points_against");

                    b.Property<int?>("SchedulePointsFor")
                        .HasColumnType("int")
                        .HasColumnName("schedule_points_for");

                    b.Property<int?>("ScheduleTies")
                        .HasColumnType("int")
                        .HasColumnName("schedule_ties");

                    b.Property<decimal?>("ScheduleWinningPercentage")
                        .HasColumnType("decimal(18,17)")
                        .HasColumnName("schedule_winning_percentage");

                    b.Property<int?>("ScheduleWins")
                        .HasColumnType("int")
                        .HasColumnName("schedule_wins");

                    b.ToTable("TeamSeasonScheduleTotals", (string)null);
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Association", b =>
                {
                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Season", "FirstSeasonIdNavigation")
                        .WithMany("AssociationFirstSeasonIdNavigations")
                        .HasForeignKey("FirstSeasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Association_Season_FirstSeasonId");

                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Season", "LastSeasonIdNavigation")
                        .WithMany("AssociationLastSeasonIdNavigations")
                        .HasForeignKey("LastSeasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Association_Season_LastSeasonId");

                    b.Navigation("FirstSeasonIdNavigation");

                    b.Navigation("LastSeasonIdNavigation");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Game", b =>
                {
                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Season", "SeasonIdNavigation")
                        .WithMany("Games")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Game_Season_SeasonId");

                    b.Navigation("SeasonIdNavigation");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.LeagueSeason", b =>
                {
                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Association", "LeagueIdNavigation")
                        .WithMany("LeagueSeasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LeagueSeason_League_LeagueId");

                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Season", "SeasonIdNavigation")
                        .WithMany("LeagueSeasons")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LeagueSeason_Season_SeasonId");

                    b.Navigation("LeagueIdNavigation");

                    b.Navigation("SeasonIdNavigation");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeason", b =>
                {
                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Association", "AssociationIdNavigation")
                        .WithMany("TeamSeasons")
                        .HasForeignKey("AssociationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamSeason_Association_AssociationId");

                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Season", "SeasonIdNavigation")
                        .WithMany("TeamSeasons")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TeamSeason_Season_SeasonId");

                    b.HasOne("EldredBrown.ProFootball.Net.Data.Models.Team", "TeamIdNavigation")
                        .WithMany("TeamSeasons")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamSeason_Team_TeamId");

                    b.Navigation("AssociationIdNavigation");

                    b.Navigation("SeasonIdNavigation");

                    b.Navigation("TeamIdNavigation");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Association", b =>
                {
                    b.Navigation("LeagueSeasons");

                    b.Navigation("TeamSeasons");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Season", b =>
                {
                    b.Navigation("ParentIdNavigations");

                    b.Navigation("AssociationFirstSeasonIdNavigations");

                    b.Navigation("AssociationLastSeasonIdNavigations");

                    b.Navigation("Games");

                    b.Navigation("LeagueSeasons");

                    b.Navigation("TeamSeasons");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Team", b =>
                {
                    b.Navigation("TeamSeasons");
                });
#pragma warning restore 612, 618
        }
    }
}
