// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EldredBrown.ProFootball.Net.Data.Migrations
{
    [DbContext(typeof(ProFootballDbContext))]
    partial class ProFootballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Season", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("Year")
                    .HasColumnType("int");

                b.Property<int>("NumOfWeeksScheduled")
                    .HasColumnType("int");

                b.Property<int>("NumOfWeeksCompleted")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Season");
            });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.League", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("ShortName")
                    .IsRequired()
                    .HasColumnType("nvarchar(5)")
                    .HasMaxLength(5);

                b.Property<string>("LongName")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)")
                    .HasMaxLength(50);

                b.Property<int>("FirstSeasonYear")
                    .HasColumnType("int");

                b.Property<int?>("LastSeasonYear")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("League");
            });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeagueName")
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("FirstSeasonYear")
                        .HasColumnType("int");

                    b.Property<int?>("LastSeasonYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Conference");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LeagueName")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ConferenceName")
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("FirstSeasonYear")
                        .HasColumnType("int");

                    b.Property<int?>("LastSeasonYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Team", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.ToTable("Team");
            });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GuestScore")
                        .HasColumnType("int");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HostScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayoffGame")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.LeagueSeason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LeagueName")
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SeasonYear")
                        .HasColumnType("int");

                    b.Property<int>("TotalGames")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<decimal?>("AveragePoints")
                        .HasColumnType("decimal(18,16)");

                    b.HasKey("Id");

                    b.ToTable("LeagueSeason");
                });
            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeason", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("TeamName")
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("SeasonYear")
                    .HasColumnType("int");

                b.Property<string>("LeagueName")
                    .HasColumnType("nvarchar(5)");

                b.Property<string>("ConferenceName")
                    .HasColumnType("nvarchar(5)");

                b.Property<string>("DivisionName")
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("Games")
                    .HasColumnType("int");

                b.Property<int>("Wins")
                    .HasColumnType("int");

                b.Property<int>("Losses")
                    .HasColumnType("int");

                b.Property<int>("Ties")
                    .HasColumnType("int");

                b.Property<int>("PointsFor")
                    .HasColumnType("int");

                b.Property<int>("PointsAgainst")
                    .HasColumnType("int");

                b.Property<decimal>("ExpectedWins")
                    .HasColumnType("decimal(18,16)");

                b.Property<decimal>("ExpectedLosses")
                    .HasColumnType("decimal(18,16)");

                b.Property<decimal?>("OffensiveAverage")
                    .HasColumnType("decimal(18,15)");

                b.Property<decimal?>("OffensiveFactor")
                    .HasColumnType("decimal(18,14)");

                b.Property<decimal?>("OffensiveIndex")
                    .HasColumnType("decimal(18,15)");

                b.Property<decimal?>("DefensiveAverage")
                    .HasColumnType("decimal(18,15)");

                b.Property<decimal?>("DefensiveFactor")
                    .HasColumnType("decimal(18,14)");

                b.Property<decimal?>("DefensiveIndex")
                    .HasColumnType("decimal(18,15)");

                b.Property<decimal?>("FinalExpectedWinningPercentage")
                    .HasColumnType("decimal(18,17)");

                b.HasKey("Id");

                b.ToTable("TeamSeason");
            });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.SeasonTeamStanding", b =>
                {
                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Conference")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("Ties")
                        .HasColumnType("int");

                    b.Property<decimal?>("WinningPercentage")
                        .HasColumnType("decimal(18,17)");

                    b.Property<int>("PointsFor")
                        .HasColumnType("int");

                    b.Property<int>("PointsAgainst")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgPointsFor")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("AvgPointsAgainst")
                        .HasColumnType("decimal(18,15)");

                    b.Property<int>("ExpectedWins")
                        .HasColumnType("decimal(18,16)");

                    b.Property<int>("ExpectedLosses")
                        .HasColumnType("decimal(18,16)");

                    b.ToTable("SeasonStandings");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeasonOpponentProfile", b =>
                {
                    b.Property<string>("Opponent")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("GamePointsFor")
                        .HasColumnType("int");

                    b.Property<int?>("GamePointsAgainst")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentWins")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentLosses")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentTies")
                        .HasColumnType("int");

                    b.Property<decimal?>("OpponentWinningPercentage")
                        .HasColumnType("decimal(18,17)");

                    b.Property<int?>("OpponentWeightedGames")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentWeightedPointsFor")
                        .HasColumnType("int");

                    b.Property<int?>("OpponentWeightedPointsAgainst")
                        .HasColumnType("int");

                    b.ToTable("TeamSeasonScheduleProfile");
                });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeasonScheduleTotals", b =>
            {
                b.Property<int?>("Games")
                    .HasColumnType("int");

                b.Property<int?>("PointsFor")
                    .HasColumnType("int");

                b.Property<int?>("PointsAgainst")
                    .HasColumnType("int");

                b.Property<int?>("ScheduleWins")
                    .HasColumnType("int");

                b.Property<int?>("ScheduleLosses")
                    .HasColumnType("int");

                b.Property<int?>("ScheduleTies")
                    .HasColumnType("int");

                b.Property<decimal?>("ScheduleWinningPercentage")
                    .HasColumnType("decimal(18,17)");

                b.Property<int?>("ScheduleGames")
                    .HasColumnType("int");

                b.Property<int?>("SchedulePointsFor")
                    .HasColumnType("int");

                b.Property<int?>("SchedulePointsAgainst")
                    .HasColumnType("int");

                b.ToTable("TeamSeasonScheduleTotals");
            });

            modelBuilder.Entity("EldredBrown.ProFootball.Net.Data.Models.TeamSeasonScheduleAverages", b =>
                {
                    b.Property<decimal?>("AvgPointsFor")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("AvgPointsAgainst")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("AvgSchedulePointsFor")
                        .HasColumnType("decimal(18,15)");

                    b.Property<decimal?>("AvgSchedulePointsAgainst")
                        .HasColumnType("decimal(18,15)");

                    b.ToTable("TeamSeasonScheduleAverages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
